name: Build Firmware

on:
  push:
    branches: [main]
    tags:
      - "dwerty-*"

permissions:
  contents: write

env:
  QMK_REPO: https://github.com/Keychron/qmk_firmware.git
  QMK_BRANCH: wireless_playground
  KEYBOARD: keychron/v6_max/ansi_encoder
  KEYMAP: dvorak_qwerty

jobs:
  build:
    runs-on:
